INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-282-1561-9','TRATADO PRACTICO DE HORTICULTURA','G. Sasias y C. Chesne, M. Guedj','Omega S.A.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788472070745','Estratigrafia: principios y metodos','Juan Antonio Vera Torres','Rueda');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-00-09145-3','Sedimentologia: del proceso fisico a la cuenca sedimentaria','Alfredo Arches Miralles','CSIC');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788439727972','Como funciona la musica','David Byrne','Literatura Random');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788483229675','Introduccion a la Econometria, 3ed','Stock, James; Watson, Mark','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9786071512109','Quimica Organica','Carey, F.A.  McGraw-Hill: Mexico, 2006','McGraw-Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9786070506970','Quimica Organica','Solomons','LIMUSA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9786070506963',' Quimica Organica','Solomons, T.W.G. ','Limusa Wiley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8461090152','A La Escucha',' Jean-Luc Nancy','Nomadas');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9786077781684','®Como funcional la musica','David Byrne','Sexto piso');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8432209473','Escucha esto','Alex Ross','Seix barral');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789871622528','Oceano de sonido','David Toop','Caja negra editores');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789972209970','TURISMO, HOTELER÷A Y RESTAURANTES','VV.AA.','LEXUS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788495818331','HOTELERIA Y TURISMO: MANUAL DE ADMINISTRACI‡N HOTELERA','VV.AA.','DALY');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-987-9473-98-6','TURISMO 2.0','TOMAELLO, FLAVIA Y DUER, WALTER','EDICIONES TURISTICAS LADEVI PROTURISMO');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9786071701985','COMPETITIVIDAD DE LOS DESTINOS TUR÷STICOS','MIGUEL ANGEL ACERENZA','TRILLAS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9562389243','Contabilidad informacion y control en las empresas; SEXTA EDICI‡N','GABRIEL TORRES SALAZAR','LEGAL PUBLISHING');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-607-15-1144-7','Preparacion y Evaluacion de Proyectos','Nassir Sapag Chain, Reinaldo Sapag Chain, Jose Manuel Sapag P.','Mc Graw Hill Education');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780134436050','Introduction to Animal Science: Global, Biological, Social and Industry Perspectives','W. Stephen Damron','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-987-628-381-6','Una guerra infame La verdadera historia de la Conquista del Desierto','Andres Bonatti , Javier Valdez','Edhasa');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-607-442-021-0','Quimica, la Ciencia Central','Theodore L. Browm  ','Pearson Educacion, Mexico');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788484764311','Las Maquinas Agricolas Y Su Aplicacion','Ortiz-CaÒavate Jaime','MUNDI-PRENSA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7901-047-9','Gaia: una ciencia para curar el planeta',' James Lovelock ','Integral, Barcelona');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789870008606','Metodologias de accion social','Ezequiel Ander Egg','LUMEN HUMANITAS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781447923831','ENGLISH FOR INTERNATIONAL TOURISM COURSEBOOK. INTERMEDIATE.','Peter Strutt','Pearson ELT');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-7119-79-0','BASES METODOL‡GICAS PARA EL DIAGN‡STICO BACTERIOL‡GICO DE LAS INFECCIONES POR CAMPYLOBACTER','Heriberto Fern†ndez J., Sofia Ochoa A., Janneth Simaluiza M.','Editora Copygraph LTDA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-61132-997-1','The Maya Rain Forest Garden, eight milenia of sustanible cultivation of the tropical woodlands','Anabel Ford y Ronald Nigh','left coast press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8420007676','La evaluacion sensorial de los alimentos en la teoria y la pr†ctica','Antonio Anzaldua-Morales','Editorial Acribia s.a.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788415556114','Teatro Posdram†tico','Hans_Thies Lehmann','cendeac');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-473-4625-0','La Odisea','Homero','Gredos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-473-4624-2','La Iliada','Homero','Gredos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8480862157, 97884808','Medicina Interna de grandes animales','BP Smith','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-323-1848-3','Atlas of Equine Endoscopy','Natahn Slovis','Mosby');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('','Fackelman, Auer, Nunamaker, Bramlage, Markel, Richardson','865778264','AO Principles of Equine Osteosynthesis');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781455740062','GeorgisÔ Parasitology for veterinarians','D Bowman','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781416056706','Equine Internal Medicine','SM Reed, WM Bayly, DC Sellon (editores)','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-4160-6069-7','Diagnosis and management of lameness in the horse ','Roos & Dyson','ELSEVIER');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-4377-0867-7','Equine Surgery','Auer & Stick','ELSEVIER');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-8138-1549-7','Adams & StashakÔs Lameness in horses','Gary Baxter','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789681675318','La nueva naturaleza de los mapas : ensayos sobre la historia de la cartografia','John Brian Harley','S.L. FONDO DE CULTURA ECONOMICA DE ESPA•A');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788498411034','EN EL MUNDO INTERIOR DEL CAPITAL. PARA UNA TEORIA FILOSOFICA DELA GLOBALIZACION','PETER SLOTERDIJK','SIRUELA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788446020646','Espacio del capital. Hacia una geografia critica','David Harvey','AKAL');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788498410648','EN EL ESPACIO LEEMOS EL TIEMPO','KARL SCHLOGEL','SIRUELA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('10.1017/pab.2016.6','Journal of Paloebiology  DOI: http://dx.doi.org/10.1017/pab.2016.6','#®NOMBRE','Cambridge Univeristy press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-3-7692-6315-2','THE UNITED STATES PHARMACOPEIA - en espaÒol (USP 38 NF 33)','United States Pharmacopeia','United States Pharmacopeia');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-7133-748-1','Metodologia de la investigacion educativa','Bisquerra, Rafael ','La Muralla');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-970-10-6889-2 ','Psicologia del Desarrollo, de la infancia a la adolescencia','Papalia , Wendkos y Duskin','Mc Graw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780729583442','Introduction to Public Health: Edition 3','Mary Louise Fleming Elizabeth Parker ','Elsevier Health Sciences');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0021-4302','JA 99','Varios autores','Shinkenchiku-sha');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('2174-0356','El Croquis 144','Varios autores','El Croquis');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0327-9022','Summa+ 76','Varios autores','Donn');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0327-9022','Summa +114','Varios autores','Donn');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0327-9022','Summa+ 116','Varios autores','Donn');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0327-9022','Summa+ 126','Varios autores','Donn');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1614-4600','Detail 3 Concept','Varios autores','Detail');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-206-8540-3','Tratado de los objetos musicales','Pierre Schaeffer','Alianza Musica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-240-51-623-0','Spatial Audio','Francis Rumsey','Focal Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-240-81295-3','Audio production and critical listening','Jason Corey','Focal Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-978-611-021-1','Acustica musical y organologia','Tirso de Olozabal','Melos ediciones musicales');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-415-87828-9','Music Technology and the project studio','Dan Hosken','Routledge');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-941188-26-5','Sound Design','David Sonnenschein','Michael Wiese production');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1-56750-536-8','Acoustic Communication','Barry Truax','Ablex Publishing');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-387-09516-5','Acoustics and the Performance of Music','Jurgen Meyer','Springer');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-415-87827-2','An introduction to music technology','Dan Hosken','Routledge');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-3-95593-055-4','Loadbang: programming electronic music in Pure Data','Johannes Kreidler','Wolke');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788432209130','El ruido eterno: escuchar al siglo XX a traves de su musica ','Alex Ross','Barcelona: Seix Barral');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788438700549','Tratado de armonia','Arnold Schoenberg','Real Musical');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788493663117','Armonia','Walter Piston','Mundimusica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788438701416','Armonia del siglo XX','Vincent Persichetti','Madrid: Real Musical');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788420685458','Musica, sociedad y educacion','Christopher Small','Madrid: Alianza Musica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781315856032','Ways of Sensing. Understanding the Senses In Society','David Howes y Costance Classen','Routledge');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788446040903','Calle de sentido unico','Walter Benjamin','AKAL');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788493837594','Breve historia de la fotografia','Walter Benjamin','CASIMIRO Libros');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-8446019015','Libro de los pasajes','Walter Benjamin','Akal Ediciones Sa');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('ISSN 0265-1491','3rd Symposium on Potato Cyst Nematodes','Haydock, P.P.J. (ed)',' AAB Office The Warwick Enterprise Park, Wellesbourne, Warwick CV35 9EF, UK');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-987-629-126-2','La viena de fin de siglo','Carl Schorske','editorial siglo XXI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9875580163','El color del rio','Susana Silvestri','Prometeo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-16011-32-2','Terror y utopia','Karl Schlogel','Acantilado Quaderns Crema, S. A . U.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788498410648','en el espacio leemos el tiempo','Kar Schlogel','siruela');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-347-686-6','Historia del teatro en Chile (1941-1990)','Juan Andres PiÒa','taurus');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781616890681','Le Corbusier Redrawn','SooJin (Steven) Park','Princeton Architectural Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780262521246','A Concrete Atlantis','Reyner Banham','The MIT Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788430938698','CINCO CARAS DE LA MODERNIDAD: MODERNISMO, VANGUARDIA, DECADENCIA, KITSCH, POSTMODERNISMO','Matei Calinescu','Tecnos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0632063789','Introduction to Ore-Forming Processes','Laurence Robb','Blackwell Science Ltd');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1107022225','Ore Deposit Geology','John Ridley','Cambridge University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978 8489882089','Teoria de los colores','JOHANN WOLFGANG VON GOETHEˇ,','Colegio oficial de aparejadores y arquitectos tecnic');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-3936646368','Eric Fischl: The Krefeld-Project','Robert Rosenblum','Kerberˇ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-3936646368','Eric Fischl: The Krefeld-Project','Robert Rosenblum','Kerberˇ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-460-1083-6','Diccionario Akal del color ','Rosa Gallegos/ Juan Carlos Sanz','akal');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-7953-628-2','El color. Un metodo para dominar el arte de combinar colores','Betty Edwards','Urano');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-8191','La Pintura Encarnada','Georges Didi-Huberman ','pre-textos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978 8881581177','Boltanski','Christian Boltanski','charta');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-939902-7-5','El siglo del Collage. Una apreciacion radical','Jose Francisco Yras','elba');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-96299-40-6','Un arte contextual','Paul Ardenne','cendeuc');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978 841 530 3510','David Hockeney: El gran Mensaje','David Hockeney','la fabrica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978 847 844 2102','Asi lo veo Yo','David Hockeney','Siruela');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0500275351','Lucian Freud Paintings','Robert Hughes','Thames & Hudson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-96898','Ante la Imagen','Georges Didi-Huberman ','cendeuc');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978 84 252 2289-4','Colores, Historia y significado','Anne Varichon','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('bpm512.a3','trigonometria','sullivan','pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1416061304','Infectious Diseases of the Dog and Cat',' Craig E. Greene DVM MS DACVIM ','Saunders');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-8138-1798-9','Schalms Veterinary Hematology','Douglas J. Weiss (Editor), K. Jane Wardrop (Editor)','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781437701739','Veterinary Hematology: A Diagnostic Guide and Color Atlas','John W. Harvey DVM PhD DACVP (Autor)','Elsievier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('521790697','Clinical Biochemistry of Domestic Animals',' Jiro Jerry Kaneko (Editor), John W. Harvey (Editor), Michael L. Bruss (Editor)','Elsievier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1118611272','Exotic Animal Hematology and Cytology',' Terry W. Campbell (Author)','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0323044684','Atlas of Canine and Feline Peripheral Blood Smears, 1e (Small Animal Laboratory Essentials)',' Amy C. Valenciano DVM MS DACVP (Author), Rick Cowell (Author), Theresa Rizzi (Author), Ronald D. Ty','Mosby');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-118-47273-6','Veterinary Hematology and Clinical Chemistry,','Mary Anna Thrall (Editor), Glade Weiser (Editor), Robin Allison (Editor), Terry W. Campbell (Editor)','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1455740833','Canine and Feline Cytology: A Color Atlas and Interpretation Guide',' Rose E. Raskin DVM PhD DACVP (Author), Denny Meyer DVM DACVIM DACVP (Author)','Saunders');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-4443-4836-1','Sedimentology and Sedimentary Basins: From Turbulence to Tectonics','Mike R. Leeder','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-521-51664-8','Structural Geology','FOSSEN Haakon','Cambridge University Press ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789567770106','Atlas para la identificacion de elementos parasitarios microscopicos en deposiciones','Patricio Torres H., Maria Isabel Jercic L. y colaboradores','Instituto de Salud Publica de Chile, Ministerio de Salud, Gobierno de Chile');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-206-6465-1','Un siglo de musica grabada','Timothy Day','Alianza Musica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-206-8207-5','La interpretacion historica de la musica','Lawson y Stowell','Alianza Musica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-206-6308-1','Historia de la Musica occidental','Grout - Palisca','Alianza Musica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-206-6468-2','La musica en la epoca Barroca','Bukofzer','Alianza Musica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1505634644','Biomimicry Resource Handbook','Dayna Baumeister','CreateSpace');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781597267151','Biophilic Cities: Integrating Nature Into Urban Design and Planning','Tim Beatley','Island Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8488386737','Glenn Murcutt Feathers Of Metal','Glenn Murcutt ','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789569082009','Arquitectura: Critica y Nueva êpoca','Enrique Browne','Stoq');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386809','STEVEN HOLL, CONCEPTOS Y MELOD÷AS','STEVEN HOLL','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386793','SELGASCANO, VACILANTE NATURALEZ','SELGASCANO','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386786','JOAO LUIS CARRILHO DA GRACA, TRAZAR CONEXIONES, CONSTRUIR PAUTAS','JOAO LUIS CARRILHO DA GRACA','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425227097','Arquitectura y Critica','Josep Maria Montaner','GG');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425227097','Arquitectura y Critica','Josep Maria Montaner','GG');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425226267','Los ojos de la piel. La arquitectura y los sentidos','Juhani Pallasmaa','GG');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386762','SMILJAN RADIC, EL JUEGO DE LOS OPUESTOS','SMILJAN RADIC','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386816','MVRDV, CIUDAD EVOLUTIVA','MVRDV','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386779','ALVARO SIZA, LECCIONES MAGISTRALES','ALVARO SIZA','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386755','Caruso St John, RUDA SUTILEZA','Caruso St John','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386670','Studio Mumbai, MANERAS DE HACER Y DE FABRICAR','Studio Mumbai','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386649','SANAA, ARQUITECTURA INORGANICA','SANAA (Sejima + Nishizawa)','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386632','Aires Mateus, CONSTRUIR EL MOLDE DEL ESPACIO','Aires Mateus','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386656','Valerio Olgiati, AFINADAS DISCORDANCIAS','Valerio Olgiati','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386618','Sou Fujimoto, TEOR÷A E INTUICI‡N, MARCA Y EXPERIENCIA','Sou Fujimoto','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9783869223360','Constructores Inmigrantes. Transferencia de Alemania a Chile','Renato DAlenon, Francisco Prado','Ediciones UC');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386748','Sean Godsell, RUDA SUTILEZA','Sean Godsell','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386724','RCR Arquitectes, ABSTRACCI‡N POêTICA','RCR Arquitectes','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386717','Mansilla+TuÒon, GEOMETR÷AS ACTIVAS','Mansilla+TuÒon','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386700','Bevk Perovi&#263;, CONDICIONALISMO','Bevk Perovi&#263;','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386694','Neutelings Riedijk, CONVENCIONES E IDENTIDAD','Neutelings Riedijk','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386823','DAVID CHIPPERFIELD, FIGURA Y ABSTRACCI‡N','DAVID CHIPPERFIELD','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788488386625','Herzog & de Meuron, PROGRAMA, MONUMENTO, PAISAJE','Herzog & de Meuron','EL CROQUIS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788447033027','ECONOMIA URBANA Y REGIONAL: INTRODUCCION A LA GEOGRAFIA ECONOMICA','FERNANDO RUBIERA MOROLLON','S.L. CIVITAS EDICIONES');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1-57230-049-3','Spatial Behavior: A Geographic Perspective','Reginald G. Golledge & Robert J. Stimson','The Guilford Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-9412-06-6','Ecologia Forestal: Bases para el manejo sustentable y conservacion de los bosques nativos de Chile','C. Donoso, ME Gonz†lez, A. Lara (editores)','Ediciones UACh (Universidad Austral de Chile)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-220-366-1','Gestion del Cuidado en Enfermeria.','Ayala, Ricardo; Torres, Cristina y Calvo, M Julia','Mediterraneo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-220-366-1','Gestion del Cuidado en Enfermeria.','Ayala, Ricardo; Torres, Cristina y Calvo, M Julia','Mediterraneo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Aprender a Cuidar. Didactica del Proceso de Enfermeria.','Ayala, Ricardo y Messing, Beate','Mediterraneo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Aprender a Cuidar. Didactica del Proceso de Enfermeria.','Ayala, Ricardo y Messing, Beate','Mediterraneo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Aprender a Cuidar. Didactica del Proceso de Enfermeria.','Ayala, Ricardo y Messing, Beate','Mediterraneo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-220-366-1','Gestion del Cuidado en Enfermeria.','Ayala, Ricardo; Torres, Cristina y Calvo, M Julia','Mediterraneo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Aprender a Cuidar. Didactica del Proceso de Enfermeria.','Ayala, Ricardo y Messing, Beate','Mediterraneo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788483223895','Geomorfologia','Mateo Gutierrez Elorza','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-7770-10-6','Atlas para la identificacion de elementos parasitarios microscopicos en deposiciones','Maria Isabel Jercic Lara - Patricio Torres Hevia','Instituto de Salud Publica de Chile, Ministerio de Salud');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780415424073','Sitte, Hegemann and the Metropolis: Modern Civic Art and International Exchanges','Charles C. Bohl, Jean-Franáois Lejeune ',' Routledge');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0615264097','The American Vitruvius: An Architects Handbook of Civic Art','WERNER HEGEMANN, ELBERT PEETS','De Facto Publishing ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788481749137','PROYECCIONES RADIOLOGICAS Y CORRELACION ANATOMICA (6¶ ED.)','KENNETH L. BONTRAGER; J. LAMPIGNANO','ELSEVIER ESPA•A');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-118-59113-0','Techniques for Virtual Palaeontology','Mark Sutton, Imran Rahman, Russell Garwood ','Wiley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-332-448-8','®Quien le pone el cascabel al gato','Guillermo Ward Gomez','Autoedicion Financiada FC Go.Reg. Tarapac† Emelnor Impresores');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788496898417','DIDACTICA DE LA LIBERACION: ARTE CONCEPTUALISTA LATINOAMERICANO','LUIS CAMNITZER','CENDEAC');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788482110837','Teorias e Historia de la Arquitectura ','Manfredo Tafuri','Celeste');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425211713','LA ESFERA Y EL LABERINTO, Vanguardia y arquitectura de Piranesi a los aÒos 70 ','TAFURI MANFREDO','GUSTAVO GILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-036-0071-2','Arquitectura Contempor†nea','Manfredo Tafuri','Aguilar-Asuri');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-3-85881-723-5','Peter Zumthor: Buildings and Projects, 1985-2013','thomas Durisch','Scheidegger und Spiess AG, Verlag');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788429126280','Fundamentos de Economia','Krugman, Paul; Wells, Robin; Graddy, Kathryn','Reverte');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0030202865','Form in tonal music: an introduction to analysis','Douglass M. Green','Holt, Rinehart & Winston');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('ISBN-13: 978-0155062','Anthology of Musical Analysis','Charles Burkhart','Wadsworth Publishing Co Inc ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788448139988','INGENIERIA DE CARRETERAS Vol. II','Carlos Kraemer, Miguel Angel del Val','MCGRAW-HILL / INTERAMERICANA DE ESPA•A S.A.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1119991498','Handbook of Marine Craft Hydrodynamics and Motion Control','Thor I Fossen','Wiley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('471941131','Guidance and Control of Ocean Vehicles','Thor I Fossen','Wiley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9561906481','Suelos de Chile','Walter Luzio, editor','Walter Luzio');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('41545','Historia de la musica occidental de Carlos Poblete Varas','Carlos Poblete Varas','Ediciones Universitarias de Valparaiso, Universidad Catolica de Valparaiso.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-987-629-327-3','Por una pedagogia de la pregunta','Paulo Freire ,  Antonio Faundez','978-987-629-327-3');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-95897-09-1','Corpus','Jean-Luc Nancy','Arena Libros');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8437617251','Ulises','James Joyce','C†tedra');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-936743-0-4','Aprendizaje dialogico en la Sociedad de la Informacion','Adriana Aubert, Ainhoa Flecha, Carmen Garcia, Ramon Flecha y Sandra Racionero','Hipatia');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-296-075-5','Administracion y Gestion efectiva en la unidad escolar','Claudio Figueroa Lopez','Universidad de Playa Ancha');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788483223895','Geomorfologia','Mateo Gutierrez Elorza','Prentice Hall');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-936743-1','Construyendo escuelas democr†ticas','Feito Alonso, Rafael / Lopez Ruiz, Juan Ignacio','Hipatia');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7827-256-9','El legado Pedagogico del siglo XX para la escuela del siglo XXI','Jaume Trilla (coord.)','GRAO');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('6071508762','Parasitologia humana','Werner Apt. B.','Mc Graw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0 8135 1762 1','The Anthropology of Self and Behavior','Gerald Michael Erchak','Rutgers University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780521426091','New Directions in Psychological Anthropology','heodore Schwartz, Geoffrey M. White y Catherine A. Lutz','Cambridge University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('123456789','Prueba','Prueba','Prueba');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('2336-3012','Prueba','ICI','UACh');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-607-15-0744-0','Micologia - Medica Basica','Alexandro Bonifaz','McGraw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-9801-353-5','OBRAS MAESTRAS DE LA ARQUITECTURA MUNDIAL','WILL PRYCE','Blume');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-9801-539-3','100 ideas que cambiaron la arquitecura','Richard Weston','Blume');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788498015744','Leer la arquitecura, diccionario visual','Owen Hopkins','Blume');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789561411456','Bases Cientificas de la Drogadiccion','Maria Estela Andres, Jose Antonio Fuentealba, Katia Gysling. Ramon Sotomayor','Ediciones Universidad Catolica de Chile');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-8174-709-6','Metodos de investigacion clinica y epidemiologica','Josep Ma Argimon Pall†s','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1891276492','Macroevolution: Diversity, Disparity, Contingency: Essays in Honor of Stephen Jay Gould','Elisabeth S Vrba and Niles Eldredge','Paleontological Society');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780716706137','Principles of paleontology','Michael Foote and Arnold Miller','W H Freeman');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-8086-959-1','Nelson Tratado de Pediatria','Behrman','Elsevier ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1449601911','Invitation to Oceanography','Pinet, Paul','Jones & Bartlett');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0471974710','Estuaries: A Physical Introduction','Dyer, Keith','Wiley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781437719352','Obstetrics: Normal and Problem Pregnancies:','Gabbe S.','saunders');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781608313815','Fetal Monitoring Interpretation','Micki L.','Lippincott Williams and Wilkins');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9786077743231','cirugia endoscopica en ginecologia','garza leal/bustos lopez','panamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8498352738','Doppler en medicina fetal','gratacos','panamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788481021196','GRANDES CALLES','ALLAN B. JACOBS','UNIVERSIDAD DE CANTABRIA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788423333356','EL CONOCIMIENTO SECRETO ','David Hockney','Destino');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788423333356','EL CONOCIMIENTO SECRETO ','David Hockney','Destino');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9702610842','Finanzas Corporativas','Johnathan Berk, Peter DeMarzo','Pearson Chile');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9786073202527','Las Finanzas en las Empresas Multinacionales','David Eiteman, Arthur Stonehill, Michael Moffet','Pearson Chile');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-3-03778-189-0','Ecological Urbanism','Varios autores',' Harvard University Graduate School of Design  Mohsen Mostafavi y Gareth Doherty');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-939409-3-5','INTRODUCCION AL URBANISMO. LA EVOLUCI‡N DE LAS CIUDADES: LA LECCI‡N DE LA ANTIGöEDAD','MARCEL POETE','FUNDACION CAJA DE ARQUITECTOS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-60344-135-3','chilean modern architecture since 1950','Fernado Perez Oyarzun, Rodrigo Perez de Arce, Horacio Torrent Schenider','Texas A&M University Press, College Station');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('323095615','Pathologic Basis of Veterinary Disease','James F. Zachary  -  M. Donald McGavin','Mosby');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7903-917-5','Psicologia','David Myers','Medica Panamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-613-693-2','Teorias de la Personalidad','james Fadiman y Robert frager','Oxford university press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-252-2071-5','Urbanismo Bioclim†tico','Esther Higueras Garcia','Gustavo Gili- EspaÒa');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-9940-089-1','DICCIONARIO DE TERMINOS SOBRE LA CIUDAD Y LO URBANO','Lorenzo Lopez Trigal','Biblioteca Nueva SL');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789561411920','Pediatria Ambulatoria con Enfoque Integral ','Patricia Valenzuela C.; Rosario Moore','Ediciones Universidad Catolica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-220-239-9','Semiologia Pediatrica','Shonhaut L., Assef M.','Mediterr†neo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-220-323-4','Pediatria Ambulatoria','Arnoldo Quezada','Mediterr†neo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('6071502993','Desarrollo Humano','Diane Papalia','McGraw-Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-4020-8645-8','Dimensions of the Sustainable City','Jenks, Mike; Jones, Colin (Eds.)','Springer');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425220524','la ciudad generica','Rem Koolhaas','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425221910','Espacio Basura','Rem Koolhaas','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425224379','Arquitectura y politica, ensayos para mundos anternativos','JOSEP MARIA MONTANER, ZAIDA MUXI','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788432313394','LA ARQUEOLOGIA DEL SABER','MICHEL FOUCAULT','SIGLO XXI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425223860','DICCIONARO MANUAL ILUSTRADO DE ARQUITECTURA','DORA WARE, BETTY BEATY','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425224102','DIEZ EDIFICIO CANONICOS 1950-2000','PETER EISENMAN','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425223921','SENDAS ONIRICAS DE SINGAPUR, RETRATO DE UNA METROPOLIS POTEMKIM O TREINTA A•OS DE TABLA RASA','Rem Koolhaas','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425223877','2G LIBROS, LINA BOBARDI, OBRA CONSTRUIDA','OLIVIA DE OLIVEIRA','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425222924','ARQUITECTURA MODERNA EN ZONAS SISMICAS','TERESA GUEVARA','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('97884252221903','SISTENAS ARQUITECTONICOS CONTEMPORANEOS','JOSEP MARIA MONTANER','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('97884252222368','ALEGORIA DEL PATRIMONIO','FRANCOISE CHOAY','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425221200','APRENDIENDO DEL POP','DENISE SCOTT BROWN','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425221200','APRENDIENDO DEL POP','DENISE SCOTT BROWN','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425220357','IDEAS QUE HAN CONFIGURADO EDIFCIIOS','FIL HEARN','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425218514','MEGAESTRUCTURAS, FUTURO URBANO DEL PASADO RECIENTE','REYNER BANHAM','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425222719','CASA CON PATIO','GöNTER PFEIFER, PER BRAUNECK','GGILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-493-1036-9','Despues del fin del arte.El arte contempor†neo y el linde de la historia','Danto,Coleman, Arthur','Paidos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('980-276-062-5','manifiestos,proclamas y polemicas de la vanguardia literaria hispanoamericana','Osorio, Nelson','Biblioteca Ayacucho');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-334-0092-7','Estetica de la desaparicion','Virilio, Paul','Anagrama');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-4443-3334-3','Handbook of Food Safety Engineering','Da-Wen-Sun (editor)','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425223310','La ciudad','Massino Cacciari','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425221170','Atmosferas','Peter Zumthor','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425218293','La buena vida, visita guiada a las casas de la modernidad','IÒaki Abalos','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425221026','HISTORIA DE LA ARQUTECTURA MEXICANA','ENRIQE X.DE ANDA','GUSTAVO GILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425224041','Grandeza, o el problema de la talla','Rem Koolhaas','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425223617','Historia del presente inmediato, la invencion del movimiento moderno arquitectonico','Anthony Vidler','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-323-0332-6 ','Vigilar y Castigar','Michel Foucault','Siglo XXI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425224058','Cuestiones de persepcion, Fenomenologia de la arquitectura','Steven Holl','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425223273','Pensar la arquitectura','Peter Zumthor','Gusravo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425223303','Lo Ordinario','Enrique Walker','Gustavo Gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425222351','La arquitectura compuesta por partes','Anton Capitel','gustavo gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425222740','HISTORIA CRITICA DE LA ARQUITECTURA MODERNA','KENNET FRAMPTON','GUSTAVO GILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425219887','LA ARQUITECTURA MODERNA, UNA HISTORIA DESAPASIONADA','ALAN COLQUHOUN','GUSTAVO GILI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788432313394','La arqueologia del saber','Michael Foucault','Siglo XXI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788425219559','Arquitectura latinoamericana contemporanea','Hugo Segawa','gustavo gili');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-607-15-0600-9','Administracion de Operaciones. Conceptos y casos contempor†neos','Roger G. Schroeder','Mc Graw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789682428333','Color ambiental, aplicaciones en arquitectura','TOM PORTER','TRILLAS');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9783433018385','The history of the theory of structures: from arch analysis to computational mechanics','Karl-Eugen Kurrer','Ernst & Sohn');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8446024004, 97884460','Arte desde 1900: modernidad, antimodernidad, posmodernidad','Hal Foster, Rosalind E. Krauss, Yves-Alain Bois','AKAL');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-19-956356-2','URBAN ECOLOGY. Patterns, Processes, and Applications','Jari NiemelÑ, JÅrgen H. Breuste, Glenn Guntenspergen, Nancy E. McIntyre, Thomas Elmqvist, and Philip','OXFORD');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('750645520','Descriptive Physical Oceanography','Talley, L., Pickard, G., Emery, W., Swift, J.','Academic Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978956220-314-2','Obstetricia','Alfredo Perez Sanchez- Enrique Donoso','Mediterr†neo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-8164-419-7','Obras completas George Trakl','Trakl, George','Editorial Trotta S.A.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES (' 978-84-9879-18','Poesia completa','Trakl, George','Editorial Trotta S.A.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780691023939','The tower and the bridge: The new art of structural engineering','David P. Billington','princeton university press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('3433018383','The history of the theory of structures','Eugen Kurrer','wiley-vch');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-8138-1668-5','Nonthermal Processing Technologies for Food','H. Zhang; G. Barbosa-C†novas; B. Balasubramaniam; P. Dunne; D. Farkas; J. Yuan (editores) ','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-19-0648-8','Suelos de Chile','Walter Luzio','Universidad de Chile');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('3-540-31210-2','Handbook of soil analysis: mineralogical, organic and inorganic methods','Marc Pansu, Jacques Gautheyrou','Springer');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0773536655) 9780773','Circulation and the City  Essays on Urban Culture','Alexandra Boutros and Will Straw','Mc Gill-queens University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1560222719','Handbook of Potato Production, Improvement, And Postharvest Management',' J. Gopal and S. M. Paul Khurana','Haworth Pr Inc');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-839-9','Administracion de Operaciones','David Collier - James Evans','CENGAGE Learning');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-4051-9978-0','Practical Food Rheology: An Interpretive Approach','Norton, I.; Spyropoulos, F.; Cox, P. (Editores)','Wiley-Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780521743495','Urban Ecology (Ecological Reviews)','Kevin J. Gaston (Editor)','Cambridge University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-8153-4106-2','Molecular Biology of the Cell','Bruce Alberts et al','Garland');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('941022749','Ultrasound Physics Review: A Review for the Ardms SPI Exam ','Cindy Owen','Davies  (ver: http://www.amazon.com/Ultrasound-Physics-Review-Ardms-Exam/dp/0941022749/ref=dp_cp_ob_');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8531401488','Adaptabilidade Humana, Introduáao a Antropologia Ecologica.','Emilio F. Moran','EDUSP');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789871566303','La sociedad sin relato. Antrop.y estetica de la inminencia','Nestor Garcia Canclini','Katz editores');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('ISBN-13: 978-0471870','Landscape ecology','FORMAN, Richard T.T. and GODRON, Michel','Wiley & Sons Inc, New York');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('ISBN-13: 978-8482112','La arquitectura de los jardines. De la antigÅedad al siglo XX. ','FARIELLO, Francesco.','Ed.Mairea-Celeste, Madrid ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788496424586','Arquitectura del paisaje','KRAUEL, Jacobo. ','Ed. Links Structure');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788449700774','ECOLOGIA URBANA','JAUME TERRADAS','RUBES');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-970-26-0851-6','Fisica','Jerry Wilson-Anthony Buffa- Bo Lou','PEARSON educacion');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('123738741','Research Methodology in the Medical and Biological Sciences ','Petter Laake, Haakon Breien Benestad, Bjorn Reino Olsen','Academic Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9872082111','Las bases de la medicina basada en evidencias: Como leer un documento.','Greenhalgh, T., & Gimenez, J. ','Volpe/Fox');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789589181751','Epidemiologia clinica. Investigacion clinica aplicada','Alvaro Ruiz Morales y Luis Enrique Morillo Z†rate','Medica Panamericana, S.A.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1850971269','Evidence-based Dentistry: Managing Information for Better Practice',' Derek Richards, Jan Clarkson, Debora Matthews, Rick Niederman','Quintessence Publishing Co Ltd');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8445818724','Fundamentos de radiologia dental','Whaites, E.','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-470-51792-5','Statistical and Methodological Aspects of Oral Health Research','Emmanuel Lesaffre, Jocelyne Feine (Co-Editor), Brian Leroux (Co-Editor), Dominique Declerck (Co-Edit','John Wiley & Sons, Inc.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('803929498','How Many Subjects: Statistical Power Analysis in Research','Helena Chmura Kraemer, Sue Thiemann','Sage Publications, Inc');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8493558389','DiseÒo de Investigaciones Clinicas','Stephen B. Hulley. Steven M. Cummings Warren S. Browner Deborah G. Grady Thomas B. Newman','Lippincott, Willians & Wilkins');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('ISBN-10: 0-309-10213','Nutrient Requirements of Small Ruminants:Sheep, Goats, Cervids, and New World Camelids ','National Research Council','National Academy Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-460-1532-1','Historia de la critica literaria del siglo XX. Del formalismo al postestructuralismo','Selden, R.','Libreria Aurea Cl†sicos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8496235068','Estructuras o por que las cosas no se caen','James Edward Gordon','Calamar Edicion y DiseÒo, S.L.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788498014358','La arquitectura de la luz natural','Henry Plummer','Blume');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8425222176','Color y luz. Teoria y pr†ctica','Jorrit Tornquist','Gustavo Gili ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-321-59550-8','Undestanding Weather and Climate','Edward Aguado & James E. Burt','Prentice Hall');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Inteligencia Social','Daniel Goleman','planeta');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789879649725','MANUAL TêCNICO DE LA AMERICAN ASSOCIATION OF BLOOD BANKS (AABB)','A.A.B.B.','Z-E');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-7892-21-1','1910-2010 Antologia: Un Siglo de Dramaturgia Chilena (4 tomos)','Diaz et al','Bicentenario');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-481-6283-2','Principios de Economia','Bradley R. Schiller','Mc Graw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-481-6283-2','Principios de Economia','Bradley R. Schiller','Mc Graw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-498-0822-7 ','Calmar el tr†fico. Pasos para una nueva cultura de la movilidad urbana. ','ALFONSO SANZ ALDUAN','D.G. de Planificacion. Centro de Publicaciones, Ministerio de Fomento');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-4020-8495-9','Ecopolis, Architecture and Cities for a Changing Climate','Downton, Paul F.','Springer Verlag. Australia');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-9665807-7-X','A COLOR ATLAS OF PARASITOLOGY','JOHN SULLIVAN','UNIVERSITY OF SAN FRANCISCO sullivan@usfca.edu');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-970-10-6641-6','Sistemas de Control de Gestion','Robert Anthony','Mc Graw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-14-0759-0','Modelos del C†lculo para las Ciencias Medicas','Gonzalo Riera y Ruben Preiss','Ediciones Universidad Catolica de Chile');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1853177040','clinical management of ovarian cancer','lederman,jonathan A.','informa health care ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788448156466','Manual de Maquinaria de Construccion, 2¶ edicion (en espaÒol)','Diaz del Rio, Manuel','McGRAW HILL');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido ','Terapia Familiar y de Pareja','Roizblatt, A.','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','SueÒo: diagnostico  y tratamiento','Abdaloff, W.','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Avances en psicoterapia y cambio psiquico ','Riquelme, R.; Ahumala, E.','desconocido ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Psiquiatria y Psicologia de la Infancia y Adolescencia','Grau, A y Meneghello, J.','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Depresion, guia y terapeutica','Retamal, P.','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Salud Familiar. Un modelo de Atencion Integral en la Atencion Primaria','Hidalgo C.G. y Carrasco E.','Desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Tecnicas de Psicoterapias Dinamicas','Florenzano, R.','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocida','Trastornos Bipolares','Correa E., Silva H., Risco L.','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Fundamentos de Psiquiatria Clinica','Valdivieso F. ','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('DESCONOCIDO','Psiquiatria Clinica ','Heerlein, E.','DESCONOCIDO');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Recomendaciones terapeuticas en los trastornos mentales','Soler, J; Pere, A. ','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('desconocido','Sinopsis de la Psiquiatria ','Sadock, B. Sadock V.','desconocido');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781420052527','Advances in Food Dehydration ','Cristina Ratti (editor)','CRC Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-3-540-34191-8','Food Physics: Physical Properties - Measurement and Applications','Figura, Ludger O., Teixeira, Arthur A. ','Springer');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('GU 2005','Psicopatologia de la Mujer','Eduardo Correa , Enrique Jadresic','Mediterr†neo');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('GPU;3;2:132-133','PSIQUIATR÷A CL÷NICA EN LA UNIDAD DE CORTA ESTADIA','Mario Vidal C.','Serie Roja');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('2;4:375-378','LA ESQUIZOFRENIA CLASICA','Cesar Ojeda','C&C Ediciones');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781585623099','TEXTBOOK OF PSYCHOPHARMACOLOGY','Alan Schatzberg, Charles Nemeroff','The American Psychiatric Publishing');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('471974714','Estuaries: A Physical Introduction','Keith R. Dyer ','Wiley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('750652780','Ocean Circulation','Open University','Butterworth-Heinemann');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1577664299','Introduction to Physical Oceanography','John A. Knauss','Waveland Pr Inc');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-07-5291-7','Sin novedad en el frente','Erich Maria Remarque','Porrua');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-521-77097-2','Modern Methods of Organic Synthesis','William Carruthers and Iain Coldham','Canbridge University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7039-842-3','Literatura de Viajes. El Viejo Mundo y el Nuevo.','Garcia CastaÒeda, Salvador (coord.) ','Castalia-Ohio State University.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7584-001-9','Geografias m†gicas. Viajeros espaÒoles del siglo XIX por paises exoticos (1800-1913). ','Litvak, Lily ','Michigan, University Microfilms International.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8483321947','Diccionario Ilustrado Latin-EspaÒol-Latin','Ediciones Vox','Vox (Bibliogr†fica)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-92-75-32913-9','Metodologia de la investigacion','Elia Pineda y Eva de Alvarado','Organizacion Panamericana de la salud');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('189830916 7','The Creative City: A Toolkit for Urban Innovators ',' Charles Landry','Demos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-7524-05-1','La Comunicacion de la Ciencia en Chile','Sergio Prenafeta Jenkin','CONICYT, Menssage');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-8118-09-8','Selleccionadas muestra off de dramaturgia','Carrera, X.; Figueroa, C.','Ediciones del Temple');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-18-0544-8','La palabra comprometida Tomo II','Ictus','Don Bosco');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-261-018-7','Teatro y dictadura','Andrade, Elba; Fuentes, Walter.','Ediciones documentos');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-18-0543-X','La palabra comprometida Tomo I','Ictus','Don Bosco');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-303-017-6','Antologia critica de la dramaturgia anarquista en Chile','Pereira P., Sergio','U.de Santiago');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-211-120-2','Teatro chileno','Benavente, David','Chileamerica CESOC');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-7159-62-9','Antologia Subjetiva','Diaz, Jorge','Red Internacional del Libro');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8483101424','Salon de belleza','Mario Bellatin','Tusquets');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('980-317-175-5 ','Ciudadanias del miedo','Susana Rotker','Editorial Nueva Sociedad');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1-930744-08-0','Espacio urbano, violencia y comunicacion en America Latina ','Mabel MoraÒa(ed)','Pittsburg.PA:Instituto Internacional de Literatura Iberoamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1205-7533',' 1983. Catalogue of the living BIVALVIA of the eastern Pacific Ocean: Bering Strait to C','Bernard,F.R.','Can. Spec. Publ. Fish. Aquat. Sci.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('13:978-84-8174-950-2','Epidemiologia y Bioestadistica: secretos','Nordness, Robert','Elsevier EspaÒa S.A.');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('968-880-875-1','Principios d Microeconomia','Case, Karl E. y Fair, Ray C.','Pearson educacion');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0025-3154 ',' The provision of oxygen to developing eggs by female shore crabs (Carcinus maenas) ','wheatly M.G.','journal of the marine biological association of the UK');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-674-53891-7 ','Looking at Cities','Allan Jacobs','Cambridge, MA: Harvard University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-344-2148-8','La Regulacin Economica de los Servicios Publicos (2 Ejemplares)','Miguel Angel Lasheras','Ariel');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-306-0477-4','La cultura: todo lo que hay que saber','Dietrich Schwanitz','Taurus ediciones');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES (' 84-335-2501-8','El Capitalismo y la moderna teoria social','Giddens, Anthony','Labor (Barcelona)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788445815618','Actividades de la vida diaria','Moruro Mirales Pedro y romero Dulce maria','Masson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788445815618','Actividades de la vida diaria','Moruro Mirales Pedro y romero Dulce maria','Masson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-8114-75-6','Dramaturgia chilena contempor†nea. 7 autores.','Griffero, Ramon. Editor y prologuista','Universidad Arcis');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-8432-603-9','Arte poetica. Seis conferencias','Borges, Jorge Luis','Critica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-8425-10-1','Ulises o no seguida de Frontera','Escobar Vila, Benito','ciertopez');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-8425-06-3','Miradas lastimeras no quiero','Radrigan, Flavia','ciertopez');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('ISBN: 9788481749465 ','INTERRELACIONES NANDA, NIC Y NOC. Diagosticos enfermeros, resultados e intervenciones ',' Johnson, M. / Bulechek, G.M. / Butcher, H. / Maas, M.L. / McCloskey Dochterman, J. / Moorh','elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788877548603','A TALE OF TWO CITIES (15 COPIAS)','CHARLES DICKENS','VICENS VIVES');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781405074544','EMMA (15 COPIAS)','JANE AUSTEN','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781405080620','SENSE AND SENSIBILITY (15 COPIAS)','JANE AUSTEN','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781405076821','GREAT EXPECTATIONS ','CHARLES DICKENS','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978140500230026000','MIDDLE MARCH (15 COPIAS)','GEORGE ELIOT','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781405077095','WUTHERING HEIGHTS (15 COPIAS)','EMILY BRONTEE','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781405077033','The Great Gatsby (15 copias)','F. Scott Fitzgerald ','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978140500230026000','MOBY DICK (15 COPIAS)','HERMAN MELVILLE ','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781405077033','The Great Gatsby ','F. Scott Fitzgerald ','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9781405080057','Teaching Reading Skills in a Foreign Language','Christine Nuttall','Macmillan');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780521799607','Laughing Matters','Peter Medgyes ','Cambridge University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780521793773','Motivational Strategies in the language classroom ','Zoltan Dîrnyei','Cambridge University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9780521281546','Communicative Language Teaching ','William Littlewood','Cambridge University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('470712376','Organic Synthesis: The Disconnection Approach','Stuart Warren y  Paul Wyatt','John Wiley and Sons');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-904455-43-1','Acanthamoeba: Biology and Pathogenesis ','Naveed Khan University of Nottingham, UK','Caister Academic Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8420540897','DIRECCION DE EMPRESAS INTERNACIONALES','PLA','PRENTICE HALL');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9702607639','Direccion de Marketing','Kotler','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('838502784','Applied Biopharmaceutics and Pharmacokinetics','Leon Shargel,Andrew B.C. Yu ','McGraw-Hill/Appleton & Lange');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9681669088','La etica protestante y espiritu del capitalsmo','Weber, Max','Fondo de Cultura Economica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9681660269','TRATADO LATINOAMERICANO DE SOCIOLOGIA DEL TRABAJO','Enrique De la Garza Toledo','Fondo de Cultura Economica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('1-4051-0800-2','International Trade and Agriculture','Won W. Koo; P. Lynn Kennedy','Blackwell');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('na','Veterinary Clinical Pathology. An integrated undergraduate course','Ceron J y col.','informacion en:  http://www.clinpathcd.com/');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8481747874','Clasificacion de intervenciones de Enfermeria','Mc Closkey - Bulechek','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-284-530-4','NIIF vs PCGA en Chile','Valenzuela Acevedo, Marcelo','Edimetri Ril Editores');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8481747882','Clasificacion de resultados de Enfermeria','Moorhead y Johnson','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8480862017',' Modelos y teorias en Enfermeria  ','Marriner - Raile','Elsevier Mosby');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8448605411','Planes de cuidados y documentacion clinica en enfermeria','Carpenito-Moyet','McGrawHill Interamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8481746401','Diagnosticos enfermeros, resulatados e intervenciones: Interrelacin Nanda ','Johnson','Harcourt');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-486-0230-7','Fundamentos de Enfermeria. Conceptos, proceso y pr†ctica','B†rbara Kozier','Mc Grawhill. Interamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('444507566','Data analysis methods in physical oceanography','Emery, W. J., & R. E. Thomson','Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-466-0','Direccion moderna de organizaciones','Joaquin Rodriguez Valencia','CENGAGE Learning (Pag 5)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-623-X','Gestion y conocimiento en organizaciones que aprenden','Eduardo Soto/ Alons Sauquet ','CENGAGE Learning (Pag. 16)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-476-8','Administracion moderna de personal','Joaquin Rodriguez Valencia','CENGAGE Learning (Pag. 25)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-463-6','Liderazgo: Teoria, Aplicacion y Desarrollo de Habilidades','Robert N. Lussier y Christopher Achua','CENGAGE Learning (Pag. 10)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970.686.813.5','Administracion: Un enfoque basado en competencias','Don Hellriegel, Susam Jackson et al.','CENGAGE Learning (Pag 4)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-229-3','Introduccion a la administracion con un enfoque de sistemas','Joaquin Rodriguez Valencia','CENGAGE Learning (Pag 9)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-814-3','Administracion de operaciones: Bienes, Servicios y Cadenas de valor','David Collier/ James Evans','CENGAGE Learning (Pag. 23)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-031-2','Administracion de produccion y operaciones','NormanGaither/Greg Frazier','CENGAGE Learning (Pag. 22)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-753-8','Teoria y diseÒo organizacional','Richard L. Daft','CENGAGE Learning (Pag. 12)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-836-4','Administracion y control de calidad','James R.Evans/William M. Lindsay','CENGAGE Learning (Pag. 22)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-500-4','Introduccion a la administracion','Richard L. Daft','CENGAGE Learning (Pag. 13)');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('92/1/131811-4','State of the Worlds Cities Report 2006/7 ','Naciones Unidas -Habitat','Naciones Unidas');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-0-9688543-1-0','Environmental Psychology: Principles and Practice ','Robert Gifford ','Optimal Books');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('950-05-0864-8','Teatro Latinoamericano de los 70','Pelletieri, Osvaldo','Ed. del Corregidor');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('950-556-349-3','Obra dram†tica','Discepolo, Armando','Galerna');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9502303539','Armando Discepolo Obra dram†tica','Pelletieri, Osvaldo','Eudeba');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9502304659','Armando Discepolo Obra dram†tica II','Pelletieri, Osvaldo','Eudeba');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('950-05-1536-9','la Nona','Cossa, Roberto','ed.del Corregidor');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('958-699-017-6','Introduccion a la ingenieria','Pablo Grech','Prentice Hall');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-55581-380-2','Diagnostic Medical Parasitology (solilcitar 3 ejemplares)','Lynne Shore Garcia, LGS & Associates','ASM Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-55581-147-1','The Microsporidia and Microsporidiosis','Murray Wittner','ASM Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-1-55581-154-9','Practical Guide to Diagnostic Parasitology (solicitar 3 ejemplares)','Lynne Shore Garcia','ASM Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-987-500-114-5','Reensamblar lo social','Latour, Bruno','manantial - argentina');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-8489-295-3','Teatro y poder en la epoca de Carlos II. Fiestas en torno a...','Farre, Judith (ed.)',' Iberoamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-7635-717-0','Critica del conocimiento litarario','Bobes, Carmen','Arco');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('13-978-970-10-6106-0','Administracion Financiera Internacional','Cheol S. Eun y Bruce G. Resnick','McGraw-Hill Interamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789871220854','NUNCA FUIMOS MODERNOS. ENSAYOS DE ANTROPOLOGiA SIMêTRICA','Latour, Bruno','Siglo XXI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8474327873','LA ESPERANZA DE PANDORA','Latour, Bruno','GEDISA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-521-83641-7','Designing Economic Mechanisms','Leonid Huwicz y Stanley Reiter','Cambridgr University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789871283576','Antropologia de la imagen','Hans Belting','Katz editores');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('999-999-999-9','Obras reunidas','Alfonso Alcalde','Altazor ()');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('201180758','Digital image Processing','R.C. Gonzalez; R.E. Woods','Prentice Hall');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-282-780-1','Teatro en Chile','Luis Pradenas','LOM');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-14-0689-6','TêCNICAS ARGUMENTATIVAS','Monica Perez y Olly Vega','Universidad Catolica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('321414527','Microeconomics','Jeffrey Perloff','Addison Wesley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9681859081','La Consultoria de Empresas','Romero Samuel','Limusa');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9682444241','Manual de Instalaciones a Gas','Lesur Luis','Trillas');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-7173-27-3','Las especies arboreas de los bosques templados de Chile y Argentina.Autoecologia de','Claudio Donoso','Marisa Cuneo Ediciones');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9788480047128','Antropologia del parentesco y de la familia ','Parkin, Robert / Stone, Linda','Editorial Universitaria Ramon Areces, Madrid');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0 7506 57170','Urban design street and square','Cliff Moughtin','Architectural press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-87420-903-x','remaking the urban waterfront','Urban land Institute','Urban Land Institute');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-486-0484-9','Manual de Diagnosticos de Enfermeria (edicion 11 o 10)','Carpenito Lynda ','Mc Graww-Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-220-214-3','MANUAL DE URGENCIAS MêDICAS','CUBILLOS, LORENZO','MEDITERRANEO');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','AUTOAPRENDIZAJE DE LA ELECTROCARDIOGRAF÷A','FASCE HENRY, EDUARDO','ED. UNIVERSIDAD DE CONCEPCI‡N');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('844581759','Atlas de Anatomia Humana','Netter, F.H.','ELSEVIER-MASSON');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('968230118','Historia de la Sexualidad.  Tres Volumenes','Michel Foucault','Siglo XXI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('987-98701-4-X','Vigilar y Castigar','Michel Foucault','Siglo XXI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-956-8637-00-2','Auditoria tributaria','Vicente Salort S.','Edimetri');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-205-3673-3','La Gestion Estrategica de los Recursos Humanos','Valle Cabrera, Ramon J. (coord)','Pearson - Prentice Hall; Madrid');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('950-641-244-8','Recursos Humanos Champions','Ulrich, Dave','Granica; Buenos Aires');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('950-641 - 317 - 7','Direccion Estrategica de Recursos Humanos: Gestion por Competencias','Alles, Martha A. ','Granica, Buenos Aires');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('950 - 641 - 123 - 9','Desarrollo del Talento Humano: Basado en Competencias','Alles, Martha A.','Granica, Buenos Aires');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-205-4570-8','Gestion por Competencias.  Un modelo estrategico para la direccion de Recursos Humanos','Javier Fern†ndez Lopez','F.T. Prentice Hall - Madrid');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970 - 26 - 0641 - 1','Administracion de Recursos Humanos','R. Wayne Mondy y Robert M. Noe','Mexico D.F. Pearson Educacion Prentice Hall');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7738-478-6','Historia breve de la poetica (Version Luis Alburquerque)','Dolezel, Lubomir','Sintesis');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('UKICGEB/bsf-id5920','Integrated food safety and veterinary public health','s. Buncic','CABI');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7738-892-0','Como se comenta una obra de teatro.','Garcia Barrientos, Jose','Sintesis');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8437503175','Teatro Chileno Contempor†neo','Antologia','Madrid: Fondo de Cultura Economica');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8430625348','El teatro hispanoamericano','G†lvez Acero, Marina','Madrid: Taurus');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('987-584-052-1','Hacer ciudad la construccion de las metropolis','C†tedra Arq. Enrique Garcia Espil','Nobuko');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-8019-830-1','RPG. PRINCIPIOS DE REEDUCACION POSTURAL GLOBAL','SOUCHARD, PHILLIPPE E.','PAIDOTRIBO');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('978-84-8019-657-4','FUNDAMENTOS DE LAS TECNICAS DE EVALUACION MUSCULO ESQUELETICAS','PALMER, M. LYNN','PAIDOTRIBO');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8480885947','MANUAL DE CONSULTOR÷A','TOM LAMBERT','GESTION 2000');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Robotica, Control, Deteccion, Vision e Inteligencia','Fu, K.S., R.C. Gonzalez y C.S.G. Lee','McGraw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Modeling and Control of Robot Manipulators','Sciavicco, L., B. Siciliano','Mc Graw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8420535745','Robots y Sistemas Sensoriales','F torres; S.T. Puente y otros','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8420529931','Organizacion y Arquitectura de Computadores','William Stallings','Prentice Hall');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8497322940','Fundamentos de los Computadores','Pedro de Miguel Anasagasti','PARANINFO');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0','Fundamentos de Robotica','Barrientos A., L.F. PeÒin, C. Balaguer y R. Aracil','Mc GRaw Hill');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9789702607724','Robotica','John J. Craig','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8483222965','Teleoperacion y Telerobotica','Jesus M. Gomez de Gabriel','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8483222957','Redes Neuronales, Autom†tica y Robotica ','Edgar Nelson S†nchez Camperos','Pearson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('','Transiciones de la Familia (REVISAR EDICIONES POSTERIORES A 2000)','Falicov; C.','AMORRORTU');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('848174427-1','Enfermeria oncologica','Otto, S.E.','ELSEVIER');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('844581159-2','Manual de Nefrologia Clinica','Botella, J','ELSEVIER-MASSON');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('848174578-2','Manual de nefrologia clinica','Lorenzo, V','ELSEVIER');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('844581082-0','500 cuestiones que plantea el cuidado del enfermo renal','Andreu, L','ELSEVIER-MASSON');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('844581124-2','Manual de Di†lisis','Daugirdas John','ELSEVIER-MASSON ');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-686-492-x','Fisica Moderna','R.Serway /C.J.Moses/C:A Moyer','Thomson Learning Publisher');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('844581187-X','Epidemiologia Clinica: Aspectos Fundamentales','Fletcher R.H. ; Fletcher S.W.; Wagner E.H.','Masson');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-7754-126-4','Como se hace la historia oral','FOLGUERA Pilar','EUDEMA');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-13-091836-9','Antropologia','EMBER Carol, Ember M., Peregrine P.','Pearson -Prentice Hall');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-8303-02-2','Historia de los Antiguos Mapuches del','Jose BENGOA','Catalonia');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-460-0234-5','Arqueologia, teorias, metodos y pract','RENFREW Colin, BAHN Paul','AKAL');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('956-244-071-0','Ambiente, bosques y gestion forestal ','Pablo Camus Gayan','LOM');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('970-613-147-7','Fisica general ','M†ximo, Antonio y Alvarenga, Beatriz','Oxford University Press');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8448146212','Principios de Finanzas Corporativas','Brealey, David y Stewart Myers','McGraw-Hill Interamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('9701046544','Finanzas Corporativas','Stephen Ross y Westerfiel Randolph','McGraw-Hill Interamericana');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('84-481-3527-X','Oleohidr†ulica','Serrano Nicol†s, Antonio','Mc Graw-Hill Profesional');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('T I :970-26-0511-3 ,TII:970-26-0512-1','Fisica Universitaria ,tomos I y II','Sears_Zemansky-Yong_Freedman','Addison_wesley');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8481747874','Clasificacion de Intervenciones de En','Joanne McCloskey Dochterman','Elsevier - Mosby');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8481747068','Diagnosticos Enfermeros 2003-2004 ','by NANDA','Elsevier - Mosby');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('8481747882','Clasificacion de Resultados de Enferm','Sue Moorhead & Marion Johnson','Mosby- Elsevier');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-393-73106-5','The urban design handbook Techniques ','Urban Design associates (Ray Gindroz)','W.W. Norton And Company, INC');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('0-631-23503-5','Designing Cities Critical readings in','Alexander R. Cuthbert','Blackwell publishing');					
INSERT INTO libros (ISBN, nombre, autor, editorial) VALUES ('','Diccionario de terminos contables fin','Salort S. Vicente','Edimetri');					
